server:
  port: 8042

app:
  name: Todo List Manager
  version: 1.0.0

logging:
  level:
    com.mipt.sem2.hw1.todolist: DEBUG

---
spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    com.mipt.sem2.hw1.todolist: DEBUG
    org.springframework: INFO
app:
  name: Todo List Manager DEV

---
spring:
  config:
    activate:
      on-profile: prod
logging:
  level:
    com.mipt.sem2.hw1.todolist: WARN